### ISSUE TITLE
Make ea-icon more child-theme friendly

### ISSUE THREAD

**Issue by clwill** [billerickson/EA-Starter#13]
I'm loving using EA-starter on my project, but I was hoping to use it as a parent theme, that way I could keep up with any changes here. There are sufficient hooks for nearly everything that I needed to use to make my child work -- except for one minor spot.

My project uses a bunch of SVG icons, and I love the functionality of ea-icon (in helper-functions). But it's not child theme friendly. A one line change makes it work with child themes though.

Simply swapping in `get_theme_file_path` does the trick.

    $icon_path = get_theme_file_path( '/assets/icons/' . $atts['group'] . '/' . $atts['icon'] . '.svg' );

I have a version with this change ready for a pull request if you'd like.

Thanks, and BTW, thank you _very_ much for this theme, I love it.

**Comment by billerickson** [comment]
I think that's a great idea. I'll patch it right now.
