### ISSUE TITLE
Can't use ACF with EA-Starter

### ISSUE THREAD

**Issue by Boa2** [billerickson/EA-Starter#17]
When I switch from the theme TwentyTwenty to EA-Starter-Master I loose the menu "Custom Fields" from my ACF Pro - so I can not use ACF with the new build of EA-Starter (downloaded today: 2019-11-29.).
I could use ACF with an  EA-Starter build that I downloaded on 2019-09-06.
Help appreciated,
Andrea

**Comment by billerickson** [comment]
You need to add `define( 'WP_LOCAL_DEV', true );` to wp-config.php, or comment out [this line](https://github.com/billerickson/EA-Starter/blob/master/inc/acf.php#L17).

This feature allows you to use ACF to create metaboxes in your development environment, but prevents anyone from editing or deleting them in the production environment.

**Comment by Boa2** [comment]
Adding define( 'WP_LOCAL_DEV', true ); did not work for me. I had to comment out the line you marked in acf.php.
Thank you!
