### ISSUE TITLE
Problem in single.php

### ISSUE THREAD

**Issue by vishalsonune** [billerickson/EA-Starter#18]
Fatal error: Uncaught Error: Call to undefined function ea_author_box() in /wp-content/themes/EA-Starter-master/single.php:41 Stack trace: #0 /wp-includes/class-wp-hook.php(288): ea_single_after_entry('') #1 /wp-includes/class-wp-hook.php(312): WP_Hook->apply_filters('', Array) #2 /wp-includes/plugin.php(478): WP_Hook->do_action(Array) #3 /wp-content/themes/EA-Starter-master/inc/tha-theme-hooks.php(191): do_action('tha_content_whi...') #4 /wp-content/themes/EA-Starter-master/inc/loop.php(34): tha_content_while_after() #5 /wp-includes/class-wp-hook.php(288): ea_default_loop('') #6 /wp-includes/class-wp-hook.php(312): WP_Hook->apply_filters('', Array) #7 wp-includes/plugin.php(478): WP_Hook->do_action(Array) #8 /wp-content/themes/EA-Starter-master/single.php on line 41

**Comment by vishalsonune** [comment]
Menu toggle and search toggle not working on archive page

**Comment by billerickson** [comment]
I fixed the undefined function issue on single posts.

The menu and search toggle work for me on archive pages ([screencast](https://a.cl.ly/YEudlLBE)). Can you look in the console to see what the issue might be in your install?

Closing this as the initial issue was addressed. If the toggles still don't work, please open a separate ticket.

Thanks
