### ISSUE TITLE
site option

### ISSUE THREAD

**Issue by jmsilcom** [billerickson/EA-Starter#19]
Hi Bill,
thanks for share your starter theme.
I'm on it and begin a work for my own website.
I've got an error whith acf site options, no options are available in back-office and i have this **error on my Query Monitor** :
`call_user_func_array() expects parameter 1 to be a valid callback, class 'BE_ACF_Customizations' does not have a method 'dynamic_layouts'`

and some others warning from ACF Pro
Can you help me to fix them ?

Thanks in advance

**See below my configuration :**

`
### wp-core ###

version: 5.3.2
site_language: fr_FR
user_language: fr_FR
timezone: +00:00
permalink: /%postname%/
https_status: false
user_registration: 0
default_comment_status: open
multisite: false
user_count: 1
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: /app/public
wordpress_size: 40,22 MB (42175626 bytes)
uploads_path: /app/public/wp-content/uploads
uploads_size: 0,00 B (0 bytes)
themes_path: /app/public/wp-content/themes
themes_size: 1,77 MB (1854861 bytes)
plugins_path: /app/public/wp-content/plugins
plugins_size: 7,39 MB (7752575 bytes)
database_size: 2,09 MB (2195456 bytes)
total_size: 51,48 MB (53978518 bytes)

### wp-dropins (1) ###

db.php: true

### wp-active-theme ###

name: Your Website (EA-Starter-master)
version: 1.0.0
author: Bill Erickson
author_website: https://www.billerickson.net
parent_theme: none
theme_features: tha_hooks, editor-styles, editor-style, admin-bar, automatic-feed-links, body-open, title-tag, post-thumbnails, menus, html5, responsive-embeds, align-wide, disable-custom-font-sizes, editor-font-sizes, disable-custom-colors, editor-color-palette, widgets
theme_path: /app/public/wp-content/themes/EA-Starter-master

### wp-themes-inactive (1) ###

Twenty Twenty: version: 1.1, author: L’équipe WordPress

### wp-mu-plugins (1) ###

WP CLEAN RESET: version: 0.9.9, author: Jean michel Silone

### wp-plugins-active (3) ###

Advanced Custom Fields PRO: version: 5.8.7, author: Elliot Condon
Query Monitor: version: 3.5.2, author: John Blackbourn
WP Template Viewer: version: 1.0.0, author: keesiemijer

### wp-media ###

image_editor: WP_Image_Editor_Imagick
imagick_module_version: 1673
imagemagick_version: ImageMagick 6.8.9-9 Q16 x86_64 2018-05-18 http://www.imagemagick.org
imagick_limits: 
	imagick::RESOURCETYPE_AREA: 2 GB
	imagick::RESOURCETYPE_DISK: -1
	imagick::RESOURCETYPE_FILE: 786432
	imagick::RESOURCETYPE_MAP: 2 GB
	imagick::RESOURCETYPE_MEMORY: 996 MB
	imagick::RESOURCETYPE_THREAD: 1
gd_version: bundled (2.1.0 compatible)
ghostscript_version: 9.06

### wp-server ###

server_architecture: Linux 4.9.93-boot2docker x86_64
httpd_software: Apache/2.4.10 (Debian)
php_version: 7.3.2 64bit
php_sapi: fpm-fcgi
max_input_variables: 3000
time_limit: 900
memory_limit: 256M
max_input_time: -1
upload_max_size: 1000M
php_post_max_size: 1000M
curl_version: 7.38.0 OpenSSL/1.0.1t
suhosin: false
imagick_availability: true
htaccess_extra_rules: false

### wp-database ###

extension: mysqli
server_version: 5.6.34
client_version: mysqlnd 5.0.12-dev - 20150407 - $Id: 7cc7cc96e675f6d72e5cf0f267f48e167c2abb23 $

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: /app/public/wp-content
WP_PLUGIN_DIR: /app/public/wp-content/plugins
WP_MAX_MEMORY_LIMIT: 256M
WP_DEBUG: false
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: false
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_LOCAL_DEV: true
DB_CHARSET: utf8
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable
mu-plugins: writable

`

**Comment by billerickson** [comment]
Thanks, this should be resolved now. Let me know if you have any more issues.

**Comment by jmsilcom** [comment]
Hi,
another one : I can't add any acf fields in my acf dashboard.

**Comment by billerickson** [comment]
Try now, it should be fixed.

That was actually a feature, not a bug. We disable the ACF editing interface so clients can't edit/delete metaboxes. You could access the ACF editing interface by adding `define( 'WP_LOCAL_DEV', true );` in wp-config.php.

People keep emailing me about this though, so I just disabled this feature on my publicly accessible starter themes ([see here](https://github.com/billerickson/EA-Starter/commit/9698ccd16bec3bc42085fa81eb810ecbe038edd5))

**Comment by jmsilcom** [comment]
hi Bill, 
thaks again. I've seen since your first comment, btw, my acf doesn't work. unable to save new fields group. is it a possible issue from json ?

**Comment by billerickson** [comment]
I'm not sure why ACF doesn't work for you. You can try deleting the acf-json folder or changing themes to see if that resolves it. 

I use ACF on every project and haven't had any issues with it and my starter themes.
