### ISSUE TITLE
First post title display

### ISSUE THREAD

**Issue by softune** [billerickson/EA-Starter#21]
After publishing a new post, The title of post is displaying on homepage.
Please solve this issue. Thank you..
![IMG_20201021_031417](https://user-images.githubusercontent.com/71947164/96647890-1ecb1500-134c-11eb-87e8-b179d38093ac.jpg)

**Comment by billerickson** [comment]
Thanks for catching that, it should be fixed now. 

I can't remember the last time I built a WP site that used the homepage as the posts page, which is why I never caught that.
