### ISSUE TITLE
[Question] Use readfile() instead of file_get_contents() for inline SVG

### ISSUE THREAD

**Issue by dhananjaygbhardwaj** [billerickson/EA-Starter#25]
Hi Bill,

In `inc/helper-functions.php,` within the `ea_icon()` function at L145, you're using the `file_get_contents()` function to inline SVG in the HTML.

I recently came around an [old ticket on WP](https://core.trac.wordpress.org/ticket/40292#comment:1) where someone suggested to use PHP `readfile()` instead of `file_get_contents()`, " _as it doesn't cause it to be copied to memory before being output_".

I know it doesn't make any visible difference in the loading, but I still wanted to hear your thoughts?

**Comment by billerickson** [comment]
That's interesting, I wasn't aware of that! I'm updating it now to use `readfile()`
